apiVersion: v1
kind: Service
metadata:
  name: email-reply-ai-service
spec:
  type: NodePort
  selector:
    app: email-reply-ai
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
